version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: user-agents
    versions:
    - 1.0.562
    - 1.0.563
    - 1.0.564
    - 1.0.565
    - 1.0.566
    - 1.0.569
    - 1.0.571
    - 1.0.572
    - 1.0.573
    - 1.0.576
    - 1.0.577
    - 1.0.578
    - 1.0.579
    - 1.0.580
    - 1.0.583
    - 1.0.584
    - 1.0.585
    - 1.0.586
    - 1.0.587
    - 1.0.590
    - 1.0.591
    - 1.0.592
    - 1.0.593
    - 1.0.594
    - 1.0.597
    - 1.0.598
    - 1.0.599
    - 1.0.600
    - 1.0.601
    - 1.0.604
    - 1.0.605
    - 1.0.606
    - 1.0.608
    - 1.0.611
    - 1.0.612
    - 1.0.613
    - 1.0.614
    - 1.0.616
    - 1.0.619
    - 1.0.620
    - 1.0.621
    - 1.0.622
    - 1.0.627
    - 1.0.629
    - 1.0.630
    - 1.0.633
    - 1.0.634
    - 1.0.635
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: puppeteer
    versions:
    - 5.5.0
    - 6.0.0
    - 7.0.0
    - 7.0.1
    - 7.0.4
    - 7.1.0
    - 8.0.0
  - dependency-name: "@types/puppeteer"
    versions:
    - 5.4.2
